ArtObject.create(name: 'Silver ewer', value: 25)
ArtObject.create(name: 'Carved bone statuette', value: 25)
ArtObject.create(name: 'Gold ring set with bloodstones', value: 250)
ArtObject.create(name: 'Carved ivory statuette', value: 250)
ArtObject.create(name: 'Silver chalice set with moonstones', value: 750)
ArtObject.create(name: 'Silver-plated steel longsword with jet set in hilt', value: 750)
ArtObject.create(name: 'Fine gold chain set with a fire opal', value: 2500)
ArtObject.create(name: 'Old masterpiece painting', value: 2500)
ArtObject.create(name: 'Jeweled gold crown', value: 7500)
ArtObject.create(name: 'Jeweled platinum ring', value: 7500)
