puts "creating dice"
Die.create(ceil: 1, floor: 1, name: 'd1', show_to_user: false)
Die.create(ceil: 2, floor: 1, name: 'd2')
Die.create(ceil: 3, floor: 1, name: 'd3')
Die.create(ceil: 4, floor: 1, name: 'd4')
Die.create(ceil: 6, floor: 1, name: 'd6')
Die.create(ceil: 8, floor: 1, name: 'd8')
Die.create(ceil: 10, floor: 1, name: 'd10')
Die.create(ceil: 20, floor: 1, name: 'd20')
Die.create(ceil: 100, floor: 1, name: 'd100')