# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

ArtObject.create(name: 'Silver ewer', value: 25)
ArtObject.create(name: 'Carved bone statuette', value: 25)
ArtObject.create(name: 'Gold ring set with bloodstones', value: 250)
ArtObject.create(name: 'Carved ivory statuette', value: 250)
ArtObject.create(name: 'Silver chalice set with moonstones', value: 750)
ArtObject.create(name: 'Silver-plated steel longsword with jet set in hilt', value: 750)
ArtObject.create(name: 'Fine gold chain set with a fire opal', value: 2500)
ArtObject.create(name: 'Old masterpiece painting', value: 2500)
ArtObject.create(name: 'Jeweled gold crown', value: 7500)
ArtObject.create(name: 'Jeweled platinum ring', value: 7500)

Coin.create(name: 'CP', value: 0.01)
Coin.create(name: 'SP', value: 0.1)
Coin.create(name: 'EP', value: 0.5)
Coin.create(name: 'GP', value: 1)
Coin.create(name: 'PP', value: 10)

Die.create(ceil: 2, floor: 1, name: 'd2')
Die.create(ceil: 3, floor: 1, name: 'd3')
Die.create(ceil: 4, floor: 1, name: 'd4')
Die.create(ceil: 6, floor: 1, name: 'd6')
Die.create(ceil: 8, floor: 1, name: 'd8')
Die.create(ceil: 10, floor: 1, name: 'd10')
Die.create(ceil: 20, floor: 1, name: 'd20')
Die.create(ceil: 100, floor: 1, name: 'd100')

Gemstone.create(description: 'opaque mottled deep blue', name: 'Azurite', value: 10)
Gemstone.create(description: 'opaque dark gray with red flecks', name: 'Bloodstone', value: 50)
Gemstone.create(description: 'transparent watery gold to rich gold', name: 'Amber', value: 100)
Gemstone.create(description: 'transparent dark green', name: 'Alexandrite', value: 500)
Gemstone.create(description: 'translucent dark green with black mottling and golden flecks', name: 'Black opal', value: 1000)
Gemstone.create(description: 'translucent lustrous black with glowing highlights', name: 'Black sapphire', value: 5000 )

MagicItem.create('max': 50, 'min': 1, name: 'potion of healing', table: 'A' )
MagicItem.create('max': 60, 'min': 51, name: 'spell scroll (cantrip)', table: 'A')
MagicItem.create('max': 70, 'min': 61, name: 'potion of climbing', table: 'A')
MagicItem.create('max': 90, 'min': 71, name: 'spell scroll (1st level)', table: 'A')
MagicItem.create('max': 94, 'min': 91, name: 'spell scroll (2nd level)', table: 'A')
MagicItem.create('max': 98, 'min': 95, name: 'potion of greater healing', table: 'A')
MagicItem.create('max': 99, 'min': 99, name: 'bag of holding', table: 'A')
MagicItem.create( 'max': 100, 'min': 100, name: 'driftglobe', table: 'A')

TreasureRule.create(max_cr: 4, min_cr: 0, treasure_type: 'individual', rules: { 'data': [{ 'max': 30, 'min': 1, 'calculations': [{ 'diceCount': 5, 'dieType': 'd6', 'coinType': 'CP' }] }, { 'max': 60, 'min': 31, 'calculations': [{ 'diceCount': 4, 'dieType': 'd6', 'coinType': 'SP' }] }, { 'max': 70, 'min': 61, 'calculations': [{ 'diceCount': 3, 'dieType': 'd6', 'coinType': 'EP' }] }, { 'max': 95, 'min': 71, 'calculations': [{ 'diceCount': 3, 'dieType': 'd6', 'coinType': 'GP' }] }, { 'max': 100, 'min': 96, 'calculations': [{ 'diceCount': 1, 'dieType': 'd6', 'coinType': 'PP' }] }] }.to_json)
TreasureRule.create(max_cr: 10, min_cr: 5, treasure_type: 'individual', rules: { 'data': [{ 'max': 30, 'min': 1, 'calculations': [{ 'diceCount': 4, 'dieType': 'd6', 'coinType': 'CP', 'multiplier': 100 }, { 'diceCount': 1, 'dieType': 'd6', 'coinType': 'EP', 'multiplier': 10 }] }, { 'max': 60, 'min': 31, 'calculations': [{ 'diceCount': 6, 'dieType': 'd6', 'coinType': 'SP', 'multiplier': 10 }, { 'diceCount': 2, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 10 }] }, { 'max': 70, 'min': 61, 'calculations': [{ 'diceCount': 3, 'dieType': 'd6', 'coinType': 'EP', 'multiplier': 10 }, { 'diceCount': 2, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 10 }] }, { 'max': 95, 'min': 71, 'calculations': [{ 'diceCount': 4, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 10 }] }, { 'max': 100, 'min': 96, 'calculations': [{ 'diceCount': 3, 'dieType': 'd6', 'coinType': 'PP', 'multiplier': 1 }, { 'diceCount': 2, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 10 }] }] }.to_json)
TreasureRule.create(max_cr: 16, min_cr: 11, treasure_type: 'individual', rules: { 'data': [ { 'max': 20, 'min': 1, 'calculations': [{ 'diceCount': 4, 'dieType': 'd6', 'coinType': 'SP', 'multiplier': 100 }, { 'diceCount': 1, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 100 }] }, { 'max': 35, 'min': 21, 'calculations': [{ 'diceCount': 1, 'dieType': 'd6', 'coinType': 'EP', 'multiplier': 100 }, { 'diceCount': 1, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 100 }] }, { 'max': 75, 'min': 36, 'calculations': [{ 'diceCount': 2, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 100 }, { 'diceCount': 1, 'dieType': 'd6', 'coinType': 'PP', 'multiplier': 10 }] }, { 'max': 100, 'min': 76, 'calculations': [{ 'diceCount': 2, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 100 }, { 'diceCount': 2, 'dieType': 'd6', 'coinType': 'PP', 'multiplier': 10 }] }] }.to_json)
TreasureRule.create(min_cr: 17, treasure_type: 'individual', rules: { 'data': [{ 'max': 15, 'min': 1, 'calculations': [{ 'diceCount': 2, 'dieType': 'd6', 'coinType': 'EP', 'multiplier': 1000 }, { 'diceCount': 8, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 100 }] }, { 'max': 55, 'min': 16, 'calculations': [{ 'diceCount': 1, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 1000 }, { 'diceCount': 1, 'dieType': 'd6', 'coinType': 'PP', 'multiplier': 100 }] }, { 'max': 100, 'min': 56, 'calculations': [{ 'diceCount': 1, 'dieType': 'd6', 'coinType': 'GP', 'multiplier': 1000 }, { 'diceCount': 2, 'dieType': 'd6', 'coinType': 'PP', 'multiplier': 100 }] }] }.to_json)
TreasureRule.create(max_cr: 4, min_cr: 0, treasure_type: 'hoard', rules: { 'data': [{ 'max': 6, 'min': 1, 'calculations': [{ 'diceCount': 0, 'dieType': 'd6', 'items': { 'type': 'gemstone', 'value': 10 }, 'multiplier': 0 }] }, { 'max': 16, 'min': 7, 'calculations': [{ 'diceCount': 2, 'dieType': 'd6', 'items': { 'type': 'gemstone', 'value': 10 }, 'multiplier': 1 }] }, { 'max': 26, 'min': 17, 'calculations': [{ 'diceCount': 2, 'dieType': 'd4', 'items': { 'type': 'art-object', 'value': 25 }, 'multiplier': 1 }] }, { 'max': 36, 'min': 27, 'calculations': [{ 'diceCount': 2, 'dieType': 'd6', 'items': { 'type': 'gemstones', 'value': 50 } }], 'multiplier': 1 }, { 'max': 100, 'min': 37, 'calculations': [{ 'diceCount': 2, 'dieType': 'd6', 'items': { 'type': 'gemstones', 'value': 10 } }, { 'diceCount': 1, 'dieType': 'd6', 'items': { table: 'A', 'type': 'magic-item', } }] }] }.to_json)
