MagicItem.create(max: 20, min: 1, name: 'potion of supreme healing', table: 'D')
MagicItem.create(max: 30, min: 21, name: 'potion of invisibility', table: 'D')
MagicItem.create(max: 40, min: 31, name: 'potion of speed', table: 'D')
MagicItem.create(max: 50, min: 41, name: '6th level spell scroll', table: 'D')
MagicItem.create(max: 57, min: 51, name: '7th level spell scroll', table: 'D')
MagicItem.create(max: 62, min: 58, name: 'Ammunition + 3', table: 'D')
MagicItem.create(max: 67, min: 63, name: 'oil of sharpness', table: 'D')
MagicItem.create(max: 72, min: 68, name: 'potion of flying', table: 'D')
MagicItem.create(max: 77, min: 73, name: 'potion of cloud giant strength', table: 'D')
MagicItem.create(max: 82, min: 78, name: 'potion of longevity', table: 'D')
MagicItem.create(max: 87, min: 83, name: 'potion of vilaity', table: 'D')
MagicItem.create(max: 92, min: 88, name: '8th level spell scroll', table: 'D')
MagicItem.create(max: 95, min: 83, name: 'horseshoes of a zephyr', table: 'D')
MagicItem.create(max: 98, min: 96, name: "Nolzur's marvelous pigments", table: 'D')
MagicItem.create(max: 99, min: 99, name: 'bag of devouring', table: 'D')
MagicItem.create(max: 100, min: 100, name: 'portable hole', table: 'D')