puts "creating magic items table H"

MagicItem.create(max: 10, min: 1, name: 'weapon, +3', table: 'H')
MagicItem.create(max: 12, min: 11, name: 'amulet of the planes', table: 'H')
MagicItem.create(max: 14, min: 13, name: 'carpet of flying', table: 'H')
MagicItem.create(max: 16, min: 15, name: 'crystal ball (very rare version)', table: 'H')
MagicItem.create(max: 18, min: 17, name: 'ring of regeneration', table: 'H')
MagicItem.create(max: 20, min: 19, name: 'ring of shooting stars', table: 'H')
MagicItem.create(max: 22, min: 21, name: 'ring of telekinesis', table: 'H')
MagicItem.create(max: 24, min: 23, name: 'robe of scintillating colors', table: 'H')
MagicItem.create(max: 26, min: 25, name: 'robe of stars', table: 'H')
MagicItem.create(max: 28, min: 27, name: 'rod of absorption', table: 'H')
MagicItem.create(max: 30, min: 29, name: 'rod of alertness', table: 'H')
MagicItem.create(max: 32, min: 31, name: 'rod of security', table: 'H')
MagicItem.create(max: 34, min: 33, name: 'rod of the pact keeper, +1', table: 'H')
MagicItem.create(max: 36, min: 35, name: 'scimitar of speed', table: 'H')
MagicItem.create(max: 38, min: 37, name: 'shield, +3', table: 'H')
MagicItem.create(max: 40, min: 39, name: 'staff of fire', table: 'H')
MagicItem.create(max: 42, min: 41, name: 'staff of frost', table: 'H')
MagicItem.create(max: 44, min: 43, name: 'staff of power', table: 'H')
MagicItem.create(max: 46, min: 45, name: 'staff of striking', table: 'H')
MagicItem.create(max: 48, min: 47, name: 'staff of thunder and lightning', table: 'H')
MagicItem.create(max: 50, min: 49, name: 'sword of sharpness', table: 'H')
MagicItem.create(max: 52, min: 51, name: 'wand of polymorph', table: 'H')
MagicItem.create(max: 54, min: 53, name: 'wand of the war mage, +3', table: 'H')
MagicItem.create(max: 55, min: 55, name: 'adamantine armor (half plate)', table: 'H')
MagicItem.create(max: 56, min: 56, name: 'adamantine armor (plate)', table: 'H')
MagicItem.create(max: 57, min: 57, name: 'animated shield', table: 'H')
MagicItem.create(max: 58, min: 58, name: 'belt of fire giant strength', table: 'H')
MagicItem.create(max: 59, min: 59, name: 'belt of frost (or stone) giant strength', table: 'H')
MagicItem.create(max: 60, min: 60, name: 'armor, +1 breastplate', table: 'H')
MagicItem.create(max: 61, min: 61, name: 'armor of resistance (breastplate)', table: 'H')
MagicItem.create(max: 62, min: 62, name: 'candle of invocation', table: 'H')
MagicItem.create(max: 63, min: 63, name: 'armor, +2 chain mail', table: 'H')
MagicItem.create(max: 64, min: 64, name: 'armor, +2 chain shirt', table: 'H')
MagicItem.create(max: 65, min: 65, name: 'cloak of arachnida', table: 'H')
MagicItem.create(max: 66, min: 66, name: 'dancing sword', table: 'H')
MagicItem.create(max: 67, min: 67, name: 'demon armor', table: 'H')
MagicItem.create(max: 68, min: 68, name: 'dragon scale mail', table: 'H')
MagicItem.create(max: 69, min: 69, name: 'dwarven plate', table: 'H')
MagicItem.create(max: 70, min: 70, name: 'dwarven thrower', table: 'H')
MagicItem.create(max: 71, min: 71, name: 'efreeti bottle', table: 'H')
MagicItem.create(max: 72, min: 72, name: 'figurine of wondrous power (obsidian steed)', table: 'H')
MagicItem.create(max: 73, min: 73, name: 'frost brand', table: 'H')
MagicItem.create(max: 74, min: 74, name: 'helm of brilliance', table: 'H')
MagicItem.create(max: 75, min: 75, name: 'horn of valhalla (bronze)', table: 'H')
MagicItem.create(max: 76, min: 76, name: 'instrument of the bards (anstruth harp)', table: 'H')
MagicItem.create(max: 77, min: 77, name: 'ioun stone (absorption)', table: 'H')
MagicItem.create(max: 78, min: 78, name: 'ioun stone (agility)', table: 'H')
MagicItem.create(max: 79, min: 79, name: 'ioun stone (fortitude)', table: 'H')
MagicItem.create(max: 80, min: 80, name: 'ioun stone (insight)', table: 'H')
MagicItem.create(max: 81, min: 81, name: 'ioun stone (intellect)', table: 'H')
MagicItem.create(max: 82, min: 82, name: 'ioun stone (leadership)', table: 'H')
MagicItem.create(max: 83, min: 83, name: 'ioun stone (strength)', table: 'H')
MagicItem.create(max: 84, min: 84, name: 'armor, +2 leather', table: 'H')
MagicItem.create(max: 85, min: 85, name: 'manual of bodily health', table: 'H')
MagicItem.create(max: 86, min: 86, name: 'manual of gainful exercise', table: 'H')
MagicItem.create(max: 87, min: 87, name: 'manual of golems', table: 'H')
MagicItem.create(max: 88, min: 88, name: 'manual of quickness of action', table: 'H')
MagicItem.create(max: 89, min: 89, name: 'mirror of life trapping', table: 'H')
MagicItem.create(max: 90, min: 90, name: 'nine lives stealer', table: 'H')
MagicItem.create(max: 91, min: 91, name: 'oathbow', table: 'H')
MagicItem.create(max: 92, min: 92, name: 'armor, +2 scale mail', table: 'H')
MagicItem.create(max: 93, min: 93, name: 'spellguard shield', table: 'H')
MagicItem.create(max: 94, min: 94, name: 'armor, +1 splint', table: 'H')
MagicItem.create(max: 95, min: 95, name: 'armor of resistance (splint)', table: 'H')
MagicItem.create(max: 96, min: 96, name: 'armor, +1 studded leather', table: 'H')
MagicItem.create(max: 97, min: 97, name: 'armor of resistance (studded leather)', table: 'H')
MagicItem.create(max: 98, min: 98, name: 'tome of clear thought', table: 'H')
MagicItem.create(max: 99, min: 99, name: 'tome of leadership and influence', table: 'H')
MagicItem.create(max: 100, min: 100, name: 'tome of understanding', table: 'H')