MagicItem.create(max: 15, min: 1, name: 'potion of superior healing', table: 'C')
MagicItem.create(max: 22, min: 16, name: '4th level spell scroll', table: 'C')
MagicItem.create(max: 27, min: 23, name: 'ammunition +2', table: 'C')
MagicItem.create(max: 32, min: 28, name: 'potion of clairvoyance', table: 'C')
MagicItem.create(max: 37, min: 33, name: 'potion of diminution', table: 'C')
MagicItem.create(max: 42, min: 34, name: 'potion of gaseous form', table: 'C')
MagicItem.create(max: 47, min: 43, name: 'potion of frost giant strength', table: 'C')
MagicItem.create(max: 52, min: 48, name: 'potion of stone giant strength', table: 'C')
MagicItem.create(max: 57, min: 53, name: 'potion of heroism', table: 'C')
MagicItem.create(max: 62, min: 58, name: 'potion of invulnerability', table: 'C')
MagicItem.create(max: 67, min: 63, name: 'potion of mind reading', table: 'C')
MagicItem.create(max: 72, min: 68, name: '5th level spell scroll', table: 'C')
MagicItem.create(max: 75, min: 73, name: 'elixir of health', table: 'C')
MagicItem.create(max: 78, min: 76, name: 'oil of etherealness', table: 'C')
MagicItem.create(max: 81, min: 79, name: 'potion of fire giant strength', table: 'C')
MagicItem.create(max: 84, min: 82, name: "quaal's feather token", table: 'C')
MagicItem.create(max: 87, min: 85, name: 'scroll of protection', table: 'C')
MagicItem.create(max: 89, min: 88, name: 'bag of beans', table: 'C')
MagicItem.create(max: 91, min: 90, name: 'bead of force', table: 'C')
MagicItem.create(max: 92, min: 92, name: 'chime of opening', table: 'C')
MagicItem.create(max: 93, min: 93, name: 'decanter of endless water', table: 'C')
MagicItem.create(max: 94, min: 94, name: 'eyes of minute seeing', table: 'C')
MagicItem.create(max: 95, min: 95, name: 'folding boat', table: 'C')
MagicItem.create(max: 96, min: 96, name: "heward's handy haversack", table: 'C')
MagicItem.create(max: 97, min: 97, name: 'horseshoes of speed', table: 'C')
MagicItem.create(max: 98, min: 98, name: 'necklace of fireballs', table: 'C')
MagicItem.create(max: 99, min: 99, name: 'periapt of health', table: 'C')
MagicItem.create(max: 100, min: 100, name: 'sending stones', table: 'C')