puts "creating magic item table F"
MagicItem.create(max: 15, min: 1, name: 'weapon, +1', table: 'F')
MagicItem.create(max: 18, min: 16, name: 'shield, +1', table: 'F')
MagicItem.create(max: 21, min: 19, name: 'sentinel shield', table: 'F')
MagicItem.create(max: 23, min: 22, name: 'amulet of proof against detection and location', table: 'F')
MagicItem.create(max: 25, min: 24, name: 'boots of elvenkind', table: 'F')
MagicItem.create(max: 27, min: 26, name: 'boots of striding and springing', table: 'F')
MagicItem.create(max: 29, min: 28, name: 'bracers of archery', table: 'F')
MagicItem.create(max: 31, min: 30, name: 'brooch of shielding', table: 'F')
MagicItem.create(max: 33, min: 32, name: 'broom of flying', table: 'F')
MagicItem.create(max: 35, min: 34, name: 'cloak of elevenkind', table: 'F')
MagicItem.create(max: 37, min: 36, name: 'cloak of protection', table: 'F')
MagicItem.create(max: 39, min: 38, name: 'gauntlets of ogre power', table: 'F')
MagicItem.create(max: 41, min: 40, name: 'hat of disguise', table: 'F')
MagicItem.create(max: 43, min: 42, name: 'javelin of lightning', table: 'F')
MagicItem.create(max: 45, min: 44, name: 'pearl of power', table: 'F')
MagicItem.create(max: 47, min: 46, name: 'rod of the pact keeper, +1', table: 'F')
MagicItem.create(max: 49, min: 48, name: 'slippers of spider climbing', table: 'F')
MagicItem.create(max: 51, min: 50, name: 'staff of the adder', table: 'F')
MagicItem.create(max: 53, min: 52, name: 'staff of the python', table: 'F')
MagicItem.create(max: 55, min: 54, name: 'sword of vengeance', table: 'F')
MagicItem.create(max: 57, min: 56, name: 'trident of fish command', table: 'F')
MagicItem.create(max: 59, min: 58, name: 'wand of magic missiles', table: 'F')
MagicItem.create(max: 61, min: 60, name: 'wand of the war mage, +1', table: 'F')
MagicItem.create(max: 63, min: 62, name: 'wand of web', table: 'F')
MagicItem.create(max: 65, min: 64, name: 'weapon of warning', table: 'F')
MagicItem.create(max: 66, min: 66, name: 'adamantine armor (chain mail)', table: 'F')
MagicItem.create(max: 67, min: 67, name: 'adamantine armor (chain shirt)', table: 'F')
MagicItem.create(max: 68, min: 68, name: 'adamantine armor (scale mail)', table: 'F')
MagicItem.create(max: 69, min: 69, name: 'bag of tricks (gray)', table: 'F')
MagicItem.create(max: 70, min: 70, name: 'bag of tricks (rust)', table: 'F')
MagicItem.create(max: 71, min: 71, name: 'bag of tricks (tan)', table: 'F')
MagicItem.create(max: 72, min: 72, name: 'boots of the winterlands', table: 'F')
MagicItem.create(max: 73, min: 73, name: 'circlet of blasting', table: 'F')
MagicItem.create(max: 74, min: 74, name: 'deck of illusions', table: 'F')
MagicItem.create(max: 75, min: 75, name: 'eversmoking bottle', table: 'F')
MagicItem.create(max: 76, min: 76, name: 'eyes of charming', table: 'F')
MagicItem.create(max: 77, min: 77, name: 'eyes of the eagle', table: 'F')
MagicItem.create(max: 78, min: 78, name: 'figurine of wondrous power (silver raven)', table: 'F')
MagicItem.create(max: 79, min: 79, name: 'gem of brightness', table: 'F')
MagicItem.create(max: 80, min: 80, name: 'gloves of missile snaring', table: 'F')
MagicItem.create(max: 81, min: 81, name: 'gloves of swimming and climbing', table: 'F')
MagicItem.create(max: 82, min: 82, name: 'gloves of thievery', table: 'F')
MagicItem.create(max: 83, min: 83, name: 'headband of intellect', table: 'F')
MagicItem.create(max: 84, min: 84, name: 'helm of telepathy', table: 'F')
MagicItem.create(max: 85, min: 85, name: 'instrument of the bards (Doss lute)', table: 'F')
MagicItem.create(max: 86, min: 86, name: 'instrument of the bards (Fochlucan bandore)', table: 'F')
MagicItem.create(max: 87, min: 87, name: 'instrument of the bards (Mac-Fuimdh cittern)', table: 'F')
MagicItem.create(max: 88, min: 88, name: 'medallion of thoughts', table: 'F')
MagicItem.create(max: 89, min: 89, name: 'necklace of adaptation', table: 'F')
MagicItem.create(max: 90, min: 90, name: 'periapt of wound closure', table: 'F')
MagicItem.create(max: 91, min: 91, name: 'pipes of haunting', table: 'F')
MagicItem.create(max: 92, min: 92, name: 'pipes of the sewers', table: 'F')
MagicItem.create(max: 93, min: 93, name: 'ring of jumping', table: 'F')
MagicItem.create(max: 94, min: 94, name: 'ring of mind shielding', table: 'F')
MagicItem.create(max: 95, min: 95, name: 'ring of warmth', table: 'F')
MagicItem.create(max: 96, min: 96, name: 'ring of water walking', table: 'F')
MagicItem.create(max: 97, min: 97, name: 'quiver of Ehlonna', table: 'F')
MagicItem.create(max: 98, min: 98, name: 'stone of good luck', table: 'F')
MagicItem.create(max: 99, min: 99, name: 'wind fan', table: 'F')
MagicItem.create(max: 100, min: 100, name: 'winged boots', table: 'F')