puts "creating magic items table I"

# get dice used in rules
d12 = Die.find_by(name: 'd12')

MagicItem.create(max: 5, min: 1, name: 'defender', table: 'I')
MagicItem.create(max: 10, min: 6, name: 'hammer of thunderbolts', table: 'I')
MagicItem.create(max: 15, min: 11, name: 'luck blade', table: 'I')
MagicItem.create(max: 20, min: 16, name: 'sword of answering', table: 'I')
MagicItem.create(max: 23, min: 21, name: 'holy avenger', table: 'I')
MagicItem.create(max: 26, min: 24, name: 'ring of djinni summoning', table: 'I')
MagicItem.create(max: 29, min: 27, name: 'ring of invisibility', table: 'I')
MagicItem.create(max: 32, min: 30, name: 'ring of spell turning', table: 'I')
MagicItem.create(max: 35, min: 33, name: 'rod of lordly might', table: 'I')
MagicItem.create(max: 38, min: 36, name: 'staff of the magi', table: 'I')
MagicItem.create(max: 41, min: 39, name: 'vorpal sword', table: 'I')
MagicItem.create(max: 43, min: 42, name: 'belt of cloud giant strength', table: 'I')
MagicItem.create(max: 45, min: 44, name: 'armor, +2 breastplate', table: 'I')
MagicItem.create(max: 47, min: 46, name: 'armor, +3 chain mail', table: 'I')
MagicItem.create(max: 49, min: 48, name: 'armor, +3 chain shirt', table: 'I')
MagicItem.create(max: 51, min: 50, name: 'cloak of invisibility', table: 'I')
MagicItem.create(max: 53, min: 52, name: 'crystal ball (legendary version)', table: 'I')
MagicItem.create(max: 55, min: 54, name: 'armor, +1 half plate', table: 'I')
MagicItem.create(max: 57, min: 56, name: 'iron flask', table: 'I')
MagicItem.create(max: 59, min: 58, name: 'armor, +3 leather', table: 'I')
MagicItem.create(max: 61, min: 60, name: 'armor, +1 plate', table: 'I')
MagicItem.create(max: 63, min: 62, name: 'robe of the archmagi', table: 'I')
MagicItem.create(max: 65, min: 64, name: 'rod of resurrection', table: 'I')
MagicItem.create(max: 67, min: 66, name: 'armor, +1 scale mail', table: 'I')
MagicItem.create(max: 69, min: 68, name: 'scarab of protection', table: 'I')
MagicItem.create(max: 71, min: 70, name: 'armor, +2 splint', table: 'I')
MagicItem.create(max: 73, min: 72, name: 'armor, +2 studded leather', table: 'I')
MagicItem.create(max: 75, min: 74, name: 'well of many worlds', table: 'I')

# this kind of rule has one row in the table proper with a bunch of subrows. It requires a second roll to figure out the real result
parent = MagicItem.create(die_id: d12.id, max: 76, min: 76, name: 'magic armor', table: 'I')
MagicItem.create(max: 2, min: 1, name: 'armor, +2 half plate', parent_id: parent.id)
MagicItem.create(max: 4, min: 3, name: 'armor, +2 plate', parent_id: parent.id)
MagicItem.create(max: 6, min: 5, name: 'armor, +3 studded leather', parent_id: parent.id)
MagicItem.create(max: 8, min: 7, name: 'armor, +3 breastplate', parent_id: parent.id)
MagicItem.create(max: 10, min: 9, name: 'armor, +3 splint', parent_id: parent.id)
MagicItem.create(max: 11, min: 11, name: 'armor, +3 half plate', parent_id: parent.id)
MagicItem.create(max: 12, min: 12, name: 'armor, +3 plate', parent_id: parent.id)

MagicItem.create(max: 77, min: 77, name: 'apparatus of kwalish', table: 'I')
MagicItem.create(max: 78, min: 78, name: 'armor of invulnerability', table: 'I')
MagicItem.create(max: 79, min: 79, name: 'belt of storm giant strength', table: 'I')
MagicItem.create(max: 80, min: 80, name: 'cubic gate', table: 'I')
MagicItem.create(max: 81, min: 81, name: 'deck of many things', table: 'I')
MagicItem.create(max: 82, min: 82, name: 'efreeti chain', table: 'I')
MagicItem.create(max: 83, min: 83, name: 'armor of resistance (half plate)', table: 'I')
MagicItem.create(max: 84, min: 84, name: 'horn of valhalla (iron)', table: 'I')
MagicItem.create(max: 85, min: 85, name: 'instrument of the bards (ollamh harp)', table: 'I')
MagicItem.create(max: 86, min: 86, name: 'ioun stone (greater absorption)', table: 'I')
MagicItem.create(max: 87, min: 87, name: 'ioun stone (mastery)', table: 'I')
MagicItem.create(max: 88, min: 88, name: 'ioun stone (regeneration)', table: 'I')
MagicItem.create(max: 89, min: 89, name: 'plate armor of etherealness', table: 'I')
MagicItem.create(max: 90, min: 90, name: 'plate armor of resistance', table: 'I')
MagicItem.create(max: 91, min: 91, name: 'ring of air elemental command', table: 'I')
MagicItem.create(max: 92, min: 92, name: 'ring of earth elemental command', table: 'I')
MagicItem.create(max: 93, min: 93, name: 'ring of fire elemental command', table: 'I')
MagicItem.create(max: 94, min: 94, name: 'ring of three wishes', table: 'I')
MagicItem.create(max: 95, min: 95, name: 'ring of water elemental command', table: 'I')
MagicItem.create(max: 96, min: 96, name: 'sphere of annihiliation', table: 'I')
MagicItem.create(max: 97, min: 97, name: 'talisman of pure good', table: 'I')
MagicItem.create(max: 98, min: 98, name: 'talisman of the sphere', table: 'I')
MagicItem.create(max: 99, min: 99, name: 'talisman of ultimate evil', table: 'I')
MagicItem.create(max: 100, min: 100, name: 'tome of the stilled tongue', table: 'I')