MagicItem.create(max: 15, min: 1, name: 'potion of greater healing', table: 'B')
MagicItem.create(max: 22, min: 16, name: 'potion of fire breath', table: 'B')
MagicItem.create(max: 29, min: 23, name: 'potion of resistance', table: 'B')
MagicItem.create(max: 34, min: 24, name: 'ammunition +1', table: 'B')
MagicItem.create(max: 39, min: 35, name: 'potion of animal friendship', table: 'B')
MagicItem.create(max: 44, min: 40, name: 'potion of hill giant strength', table: 'B')
MagicItem.create(max: 49, min: 45, name: 'potion of growth', table: 'B')
MagicItem.create(max: 54, min: 50, name: 'potion of water breathing', table: 'B')
MagicItem.create(max: 59, min: 55, name: '2nd level spell scroll', table: 'B')
MagicItem.create(max: 64, min: 60, name: '3rd level spell scroll', table: 'B')
MagicItem.create(max: 67, min: 65, name: 'bag of holding', table: 'B')
MagicItem.create(max: 70, min: 68, name: "keoghtom's ointment", table: 'B')
MagicItem.create(max: 73, min: 71, name: 'oil of slipperiness', table: 'B')
MagicItem.create(max: 75, min: 74, name: 'dust of disappearance', table: 'B')
MagicItem.create(max: 77, min: 76, name: 'dust of dryness', table: 'B')
MagicItem.create(max: 79, min: 78, name: 'dust of sneezing and choking', table: 'B')
MagicItem.create(max: 81, min: 80, name: 'elemental gem', table: 'B')
MagicItem.create(max: 83, min: 82, name: 'philter of love', table: 'B')
MagicItem.create(max: 84, min: 84, name: 'alchemy jug', table: 'B')
MagicItem.create(max: 85, min: 85, name: 'cap of water breathing', table: 'B')
MagicItem.create(max: 86, min: 86, name: 'cloak of the manta ray', table: 'B')
MagicItem.create(max: 87, min: 87, name: 'driftglobe', table: 'B')
MagicItem.create(max: 88, min: 88, name: 'goggles of night', table: 'B')
MagicItem.create(max: 89, min: 89, name: 'helm of comprehending languages', table: 'B')
MagicItem.create(max: 90, min: 90, name: 'immovable rod', table: 'B')
MagicItem.create(max: 91, min: 91, name: 'lantern of revealing', table: 'B')
MagicItem.create(max: 92, min: 92, name: "mariner's armor", table: 'B')
MagicItem.create(max: 93, min: 93, name: 'mithral armor', table: 'B')
MagicItem.create(max: 94, min: 94, name: 'potion of poison', table: 'B')
MagicItem.create(max: 95, min: 95, name: 'ring of swimming', table: 'B')
MagicItem.create(max: 96, min: 96, name: 'robe of useful items', table: 'B')
MagicItem.create(max: 97, min: 97, name: 'rope of climbing', table: 'B')
MagicItem.create(max: 98, min: 98, name: 'saddle of the cavalier', table: 'B')
MagicItem.create(max: 99, min: 99, name: 'wand of magic detection', table: 'B')
MagicItem.create(max: 100, min: 100, name: 'wand of secrets', table: 'B')